name: Build plugin zip

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        working-directory: wp-content/plugins/cv-dossier-context
        run: |
          rm -rf vendor
          composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
          composer dump-autoload -o --classmap-authoritative

      - name: Prepare build directory
        working-directory: wp-content/plugins/cv-dossier-context
        run: |
          SLUG="cv-dossier-context"
          BUILD_DIR="build/$SLUG"
          rm -rf "$BUILD_DIR"
          mkdir -p "$BUILD_DIR"
          rsync -a --delete \
            --exclude=.git \
            --exclude=.github \
            --exclude=tests \
            --exclude=docs \
            --exclude=node_modules \
            --exclude='*.md' \
            --exclude=.idea \
            --exclude=.vscode \
            --exclude=build \
            --exclude=.gitattributes \
            --exclude=.gitignore \
            --exclude=build.sh \
            --exclude=tools \
            --exclude=composer.json \
            --exclude=composer.lock \
            ./ "$BUILD_DIR/"
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"
          ZIP_NAME="$SLUG-$VERSION.zip"
          (cd build && zip -r "$ZIP_NAME" "$SLUG")
          echo "ZIP_PATH=wp-content/plugins/cv-dossier-context/build/$ZIP_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: ${{ env.ZIP_PATH }}
